providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "nodejs"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi --log-file -"
