[providers]
python = "3.12"

[phases.setup]
nixPkgs = ["...", "nodejs", "npm"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi --log-file -"
